# 连接容器内部的内嵌微型 Postgres
postgresql-hostname: localhost
postgresql-port: 5432
postgresql-database: guacamole
postgresql-username: postgres
postgresql-password: ''

# 驱动指向配置
guacd-hostname: localhost
guacd-port: 4822