[supervisord]
nodaemon=true
user=root
loglevel=info
logfile=/dev/stdout
logfile_maxbytes=0
pidfile=/run/supervisord.pid

[program:postgresql]
command=su-exec postgres postgres -D /var/lib/postgresql/data
autorestart=true
priority=1
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:guacd]
# 修正路径为 /opt/guacamole/sbin/guacd
command=/opt/guacamole/sbin/guacd -b 127.0.0.1 -f
autorestart=true
priority=2
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:tomcat]
# 使用 sh -c 运行 catalina.sh
command=/bin/sh -c "/opt/tomcat/bin/catalina.sh run"
autorestart=true
priority=3
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
